<?php


namespace app\index\common;


use think\Controller;
use think\Session;

class Base extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        //在公共初始化方法中，创建一个常量来判断用户是否登陆或者已登陆
        define('USER_ID',Session::get('user_id'));
    }

    //如果没登陆，则必须登陆
    protected function isLogin(){
        //如果登陆常量为NULL,没登陆
        if (is_null(USER_ID)){
            $this-> error('未登录，请先登录！','../index/login');
        }
    }

    //如果已经登陆，则不能登陆
    protected function alreadyLogin(){
        //如果登陆常量为NULL,没登陆
        if (!is_null(USER_ID)){
            $this-> error('已经登陆，请不要重复登录！','../index/index');
        }
    }
}